### ISSUE TITLE
Initial Relational Model

### ISSUE THREAD

**Issue by aneeshsr** [aneeshsr/propertymanager#1]
Initial Relational Model required to cover features provided in Apr 8th weekly sprint

**Comment by bhapinder** [comment]
![propertymanager relational model - propert managr](https://cloud.githubusercontent.com/assets/5365805/6951673/8589b220-d882-11e4-8da9-ce7fff3b46fd.png)

**Comment by bhapinder** [comment]
Initial Draft Relational Model

**Comment by bhapinder** [comment]
Referred the above diagram in project for relation model
